# Generated by Django 5.2.8 on 2025-11-22 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passengers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="email",
        ),
        migrations.RemoveField(
            model_name="passenger",
            name="name",
        ),
        migrations.AddField(
            model_name="passenger",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("in use", "In Use"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                ],
                default=None,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
