# Generated by Django 5.2.8 on 2025-11-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passengers", "0002_remove_passenger_email_remove_passenger_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="cost",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
