# Generated by Django 5.2.8 on 2025-11-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passengers", "0003_alter_ticket_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField(default=5, help_text="Distance in km")),
                (
                    "travel_time",
                    models.PositiveIntegerField(help_text="time in minutes"),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                (
                    "destination_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_destination",
                        to="passengers.station",
                    ),
                ),
                (
                    "start_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_start",
                        to="passengers.station",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection",
                        to="passengers.line",
                    ),
                ),
            ],
            options={
                "unique_together": {("line", "start_station", "destination_station")},
            },
        ),
    ]
