# Generated by Django 5.2.8 on 2025-11-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passengers", "0004_line_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
