# Generated by Django 5.2.8 on 2025-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passengers", "0005_line_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15),
        ),
    ]
